### ISSUE TITLE
"ManhattanModeler (DemowithTestData)"

### ISSUE THREAD

**Issue by jlxAha** [LiangliangNan/ManhattanModeler#1]
Hi, there is no folder for "ManhattanModeler (DemowithTestData)"

**Comment by LiangliangNan** [comment]
Thanks for reporting the missing folder.  Now it has been added to the repository.

**Comment by jlxAha** [comment]
I'm also doing research on large-scale 3D reconstruction, and I read your paper， it's a great work.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiangliangNan/ManhattanModeler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月21日(星期三) 凌晨0:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LiangliangNan/ManhattanModeler] "ManhattanModeler (DemowithTestData)" (#1)





 
Thanks for reporting the missing folder.  Now it has been added to the repository.

**Comment by LiangliangNan** [comment]
Thanks. Looking forward to learn that.
You may also find some of my other works on this topic😉
https://3d.bk.tudelft.nl/liangliang/publications.html
