### ISSUE TITLE
Smooth term and compactness

### ISSUE THREAD

**Issue by cd147** [LiangliangNan/ManhattanModeler#2]
Hello, Is there a lack of smooth weight when the thickness of boxes is thinner than 1m and compactness to avoid holes in the code provided?

**Comment by LiangliangNan** [comment]
Our current formulation does have a smoothness term that is designed to penalize holes and bumps. But it is not a hard constraint and thus it does not provide guarantee. 
Besides, a uniform weight is used for the current smoothness term, which is also not optimal. 
If you have any ideas to enforce closeness in the formulation, we would be very happy to discuss them and implement them into the code.
