### ISSUE TITLE
Missing wall repair

### ISSUE THREAD

**Issue by study313software** [LiangliangNan/ManhattanModeler#3]
Sorry to disturb you. But I have a question about the missing wall repair in the paper.
In the paper, the missing wall can be repaired duing this process. so that the broken model can be fixed.
![1](https://github.com/LiangliangNan/ManhattanModeler/assets/41318959/a377be11-ebe5-4011-974e-be02e2d5bcc9)
However, this model can not be repaired in the exe you provided.
Model: 
![2](https://github.com/LiangliangNan/ManhattanModeler/assets/41318959/574cfaf4-3954-4b8d-b75a-ca7422a43644)
Result in exe: 
![3](https://github.com/LiangliangNan/ManhattanModeler/assets/41318959/16d0f3c1-708b-4963-bdc8-1eb017dcfb2e)

Is there anything wrong with my exe? Or maybe the repair process is not opened in the exe? 
Looking forward to your reply. Thanks.

**Comment by LiangliangNan** [comment]
Have you tuned the parameters?
Photogrammetric point clouds have arbitrary scales, and thus, some of the parameters might need to be adjusted.
If still not solved, please send your data to the first author of the paper, and ask him to test your data.

**Comment by study313software** [comment]
Thanks for your reply. I will try to tune the parameters. By the way, may I ask the Qt version of the code? 
I see the code sln was built by VS2013. Is VS2013+ Qt5 correct for the code? 
I tried VS2019+Qt 6.5.3. But It contain lots of error.

**Comment by LiangliangNan** [comment]
So far Qt5 is supported (versions 5.6 and 5.15 have been tested, and you should have no problem using all other Qt5 versions). You can downloaded it here: https://download.qt.io/archive/qt/5.14/5.14.2/

In this distribution, project file(s) for Visual Studio 2019 are provided for compiling the code. But newer version of VS should also work (with some small adjustifications in the project setting).

**Comment by study313software** [comment]
Thanks for your reply again! 
The project was successfully built with configure: VS 2013+ QT 5.9+CGAL 4.7+ boost 1.59.0+OpenGL.

However, I wonder where is the code about  missing wall repair fuction. Could you give me some hint about this part of the code?

**Comment by LiangliangNan** [comment]
If you have any questions regarding the implementation, please contact Dr. Minglei Li at [minglei_li@126.com](mailto:minglei_li@126.com).
